version: '3.7'

services:
  api:
    image: api
    container_name: api_atletic_app
    ports:
      - '8000:8080'
    volumes:
      - '.:/app'
    command: 'npm start'
    networks:
      - internel-network
    depends_on:
      - database

  database:
    image: mysql
    container_name: database
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=@Igor2000
    networks:
      - internel-network


networks:
  iternal-network:
    driver: bridge


    